apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kite
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - kite.mini.k8
      secretName: kite-tls
  rules:
    - host: kite.mini.k8
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kite
                port:
                  number: 8080

